language: node_js

before_script:
  - npm install
  # TODO: resolve ng-draggable dependency issue and
  #   stop pushing bower components to repo
  # - node_modules/bower/bin/bower install

script:
  - grunt --gruntfile config/grunt.conf.js test
